=== player1537-forks/vcb/nfu/scene.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!-- @(#) $Id: scene.xsd,v 1.3 2005/09/21 15:42:49 hliu Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="scene_setting">
		<xs:annotation>
			<xs:documentation>scene settings for vclib</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="viewing_parameters">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="lighting">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="light" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="light_x" type="xs:float"/>
													<xs:element name="light_y" type="xs:float"/>
													<xs:element name="light_z" type="xs:float"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="half" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="half_x" type="xs:float"/>
													<xs:element name="half_y" type="xs:float"/>
													<xs:element name="half_z" type="xs:float"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="vector" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="vector_x" type="xs:float"/>
													<xs:element name="vector_y" type="xs:float"/>
													<xs:element name="vector_z" type="xs:float"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="ambient" type="xs:float" maxOccurs="unbounded"/>
										<xs:element name="diffuse" type="xs:float" maxOccurs="unbounded"/>
										<xs:element name="specular" type="xs:float" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="num_lights" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="model_view_matrix">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="element" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="m" type="xs:nonNegativeInteger"/>
													<xs:element name="n" type="xs:nonNegativeInteger"/>
													<xs:element name="value" type="xs:float"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="viewing_transform">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="eye">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="eye_x" type="xs:float"/>
													<xs:element name="eye_y" type="xs:float"/>
													<xs:element name="eye_z" type="xs:float"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="center">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="center_x" type="xs:float"/>
													<xs:element name="center_y" type="xs:float"/>
													<xs:element name="center_z" type="xs:float"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="up">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="up_x" type="xs:float"/>
													<xs:element name="up_y" type="xs:float"/>
													<xs:element name="up_z" type="xs:float"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="projection_transform">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="mode" type="xs:float"/>
										<xs:element name="near" type="xs:float"/>
										<xs:element name="far" type="xs:float"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="perspective_projection">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="fov" type="xs:float"/>
										<xs:element name="aspect" type="xs:float"/>
										<xs:element name="hither" type="xs:float"/>
										<xs:element name="yon" type="xs:float"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="orthographic_projection">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="left" type="xs:float"/>
										<xs:element name="right" type="xs:float"/>
										<xs:element name="bottom" type="xs:float"/>
										<xs:element name="top" type="xs:float"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="viewport_transform">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="width" type="xs:float"/>
										<xs:element name="height" type="xs:float"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="mcube" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="iso_value" type="xs:float"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="raycasting" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="scale">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="scale_x" type="xs:float"/>
										<xs:element name="scale_y" type="xs:float"/>
										<xs:element name="scale_z" type="xs:float"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="color_scheme" type="xs:integer"/>
							<xs:element name="iso_range">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="pos" type="xs:float" maxOccurs="unbounded"/>
										<xs:element name="size" type="xs:float" maxOccurs="unbounded"/>
										<xs:element name="opa" type="xs:float" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="num_iso_range" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="streamline" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="seeds">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="seed" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="seed_x" type="xs:float"/>
													<xs:element name="seed_y" type="xs:float"/>
													<xs:element name="seed_z" type="xs:float"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="num_seeds" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="step_size" type="xs:float"/>
							<xs:element name="num_verts" type="xs:float"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== player1537-forks/vcb/nfu/scene_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!-- @(#) $Id: scene_test.xml,v 1.2 2005/09/20 20:33:44 hliu Exp $ -->
<scene_setting xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\hliu\Desktop\scene\scene.xsd" version="0.0.1">
	<viewing_parameters>
		<lighting num_lights="2">
			<light>
				<light_x>111.1</light_x>
				<light_y>222.2</light_y>
				<light_z>333.3</light_z>
			</light>
			<light>
				<light_x>1111.1</light_x>
				<light_y>2222.2</light_y>
				<light_z>3333.3</light_z>
			</light>
			<half>
				<half_x>444.4</half_x>
				<half_y>555.5</half_y>
				<half_z>666.6</half_z>
			</half>
			<half>
				<half_x>4444.4</half_x>
				<half_y>5555.5</half_y>
				<half_z>6666.6</half_z>
			</half>
			<vector>
				<vector_x>777.7</vector_x>
				<vector_y>888.8</vector_y>
				<vector_z>999.9</vector_z>
			</vector>
			<vector>
				<vector_x>7777.7</vector_x>
				<vector_y>8888.8</vector_y>
				<vector_z>9999.9</vector_z>
			</vector>
			<ambient>1000.1</ambient>
			<ambient>1001.1</ambient>
			<diffuse>2000.2</diffuse>
			<diffuse>2002.2</diffuse>
			<specular>3000.3</specular>
			<specular>3003.3</specular>
		</lighting>
		<model_view_matrix>
			<element>
				<m>0</m>
				<n>0</n>
				<value>1111.1</value>
			</element>
			<element>
				<m>0</m>
				<n>1</n>
				<value>1111.2</value>
			</element>
			<element>
				<m>0</m>
				<n>2</n>
				<value>1111.3</value>
			</element>
			<element>
				<m>0</m>
				<n>3</n>
				<value>1111.4</value>
			</element>
			<element>
				<m>1</m>
				<n>0</n>
				<value>1111.5</value>
			</element>
			<element>
				<m>1</m>
				<n>1</n>
				<value>1111.6</value>
			</element>
			<element>
				<m>1</m>
				<n>2</n>
				<value>1111.7</value>
			</element>
			<element>
				<m>1</m>
				<n>3</n>
				<value>1111.8</value>
			</element>
			<element>
				<m>2</m>
				<n>0</n>
				<value>2222.1</value>
			</element>
			<element>
				<m>2</m>
				<n>1</n>
				<value>2222.2</value>
			</element>
			<element>
				<m>2</m>
				<n>2</n>
				<value>2222.3</value>
			</element>
			<element>
				<m>2</m>
				<n>3</n>
				<value>2222.4</value>
			</element>
			<element>
				<m>3</m>
				<n>0</n>
				<value>2222.5</value>
			</element>
			<element>
				<m>3</m>
				<n>1</n>
				<value>2222.6</value>
			</element>
			<element>
				<m>3</m>
				<n>2</n>
				<value>2222.7</value>
			</element>
			<element>
				<m>3</m>
				<n>3</n>
				<value>2222.8</value>
			</element>
		</model_view_matrix>
		<viewing_transform>
			<eye>
				<eye_x>2222.1</eye_x>
				<eye_y>2222.2</eye_y>
				<eye_z>2222.3</eye_z>
			</eye>
			<center>
				<center_x>2222.4</center_x>
				<center_y>2222.5</center_y>
				<center_z>2222.6</center_z>
			</center>
			<up>
				<up_x>2222.7</up_x>
				<up_y>2222.8</up_y>
				<up_z>2222.9</up_z>
			</up>
		</viewing_transform>
		<projection_transform>
			<mode>777</mode>
			<near>777.1</near>
			<far>777.2</far>
		</projection_transform>
		<perspective_projection>
			<fov>888.1</fov>
			<aspect>888.2</aspect>
			<hither>888.3</hither>
			<yon>888.4</yon>
		</perspective_projection>
		<orthographic_projection>
			<left>999.1</left>
			<right>999.2</right>
			<bottom>999.3</bottom>
			<top>999.4</top>
		</orthographic_projection>
		<viewport_transform>
			<width>888</width>
			<height>999</height>
		</viewport_transform>
	</viewing_parameters>
	<mcube>
		<iso_value>1111.1</iso_value>
	</mcube>
	<raycasting>
		<scale>
			<scale_x>2222.1</scale_x>
			<scale_y>2222.2</scale_y>
			<scale_z>2222.3</scale_z>
		</scale>
		<color_scheme>3</color_scheme>
		<iso_range num_iso_range="2">
			<pos>2222.4</pos>
			<pos>2222.44</pos>
			<size>2222.5</size>
			<size>2222.55</size>
			<opa>2222.6</opa>
			<opa>2222.66</opa>
		</iso_range>
	</raycasting>
	<streamline>
		<seeds num_seeds="2">
			<seed>
				<seed_x>3333.1</seed_x>
				<seed_y>3333.2</seed_y>
				<seed_z>3333.3</seed_z>
			</seed>
			<seed>
				<seed_x>3333.4</seed_x>
				<seed_y>3333.5</seed_y>
				<seed_z>3333.6</seed_z>
			</seed>
		</seeds>
		<step_size>3333.7</step_size>
		<num_verts>3333</num_verts>
	</streamline>
</scene_setting>
